version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: true

hooks:
  # On ajoute ce hook pour supprimer l'ancien WAR AVANT d'installer le nouveau
  BeforeInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: deploy.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root