version: 0.0
os: linux

files:
  - source: workflowmicropop.war
    destination: /home/ubuntu/workflowmicropop/

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root